#!/bin/bash
set -e

# TASK 14. Use the default entrypoint to create databases and users for Dex, Forgejo and Grafana
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL

    CREATE DATABASE $DEX_DB;
    CREATE USER $DEX_USER WITH ENCRYPTED PASSWORD '$DEX_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $DEX_DB TO $DEX_USER;

    CREATE DATABASE $GRAFANA_DB;
    CREATE USER $GRAFANA_USER WITH ENCRYPTED PASSWORD '$GRAFANA_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $GRAFANA_DB TO $GRAFANA_USER;

    CREATE DATABASE $FORGEJO_DB;
    CREATE USER $FORGEJO_USER WITH ENCRYPTED PASSWORD '$FORGEJO_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $FORGEJO_DB TO $FORGEJO_USER;

    \c $DEX_DB;
    ALTER SCHEMA public OWNER TO $DEX_USER;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $DEX_USER;

    \c $GRAFANA_DB;
    ALTER SCHEMA public OWNER TO $GRAFANA_USER;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $GRAFANA_USER;

    \c $FORGEJO_DB;
    ALTER SCHEMA public OWNER TO $FORGEJO_USER;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $FORGEJO_USER;
EOSQL