networks:
  portainer_net:

services:
  homer:
    image: b4bz/homer:latest
    restart: always
    networks:
      traefik_net:
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=vcc_traefik_net"
        - "traefik.http.routers.homer.rule=Host(`home.vcc.internal`)"
        - "traefik.http.routers.homer.entrypoints=web,websecure"
        - "traefik.http.routers.homer.tls=true"
        - "traefik.http.services.homer.loadbalancer.server.port=8080"
      placement:
        constraints:
          - node.role == worker
    volumes:
      - /data/configs/homer/homer.yml:/www/assets/config.yml

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    user: "0:0"
    entrypoint: ["/bin/sh", "-c", "
      apk add --no-cache ca-certificates &&
      update-ca-certificates &&
      exec /entrypoint.sh"]
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@vcc.internal"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_OIDC_CLIENT_ID: pgadmin
      PGADMIN_OIDC_CLIENT_SECRET: "{{ pgadmin_oauth }}"
      PGADMIN_CONFIG_LOCAL_SKIP_DEFAULT: "True"
    volumes:
      - /data/configs/pgadmin/config_local.py:/pgadmin4/config_local.py
      - /data/ssl/private/ca.pem:/usr/local/share/ca-certificates/ca.crt
      - /data/ssl/certs/{{ domain_name }}.crt:/usr/local/share/ca-certificates/{{ domain_name }}.crt
    networks:
      db_net:
      traefik_net:
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=vcc_traefik_net"
        - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.vcc.internal`)"
        - "traefik.http.routers.pgadmin.entrypoints=web,websecure"
        - "traefik.http.routers.pgadmin.tls=true"
        - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      placement:
        constraints:
          - node.role == worker

  portainer_agent:
    image: portainer/agent
    restart: always 
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      portainer_net:

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.portainer_agent:9001 --tlsskipverify
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=vcc_traefik_net"
        - "traefik.http.routers.portainer.rule=Host(`portainer.vcc.internal`)"
        - "traefik.http.routers.portainer.entrypoints=web,websecure"
        - "traefik.http.routers.portainer.tls=true"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      traefik_net:
      portainer_net:
