{
 "title": "Services Logs Dashboard",
 "tags": [ "logs" ],
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(container_label_com_docker_swarm_service_name)"
   },
   { "name": "log_filter", "label": "Log search" }
  ]
 },
 "panels": [
  {
   "title": "$service Logs Stream",
   "type": "logs",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "{container_label_com_docker_swarm_service_name=\"$service\"} |= \"$log_filter\""
    }
   ]
  },
  {
   "title": "$service Logs Over Time",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 0, "w": 16, "h": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({container_label_com_docker_swarm_service_name=\"$service\"} | json [6h])) by (detected_level)"
    }
   ]
  },
  {
   "title": "$service Logs Breakdown",
   "type": "piechart",
   "gridPos": { "x": 0, "y": 8, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({container_label_com_docker_swarm_service_name=\"$service\"} [6h])) by (detected_level)"
    }
   ]
  },
  {
   "title": "Error Logs Count",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 4, "h": 4 },
   "targets": [
    {
     "expr": "sum(count_over_time({container_label_com_docker_swarm_service_name=\"$service\"} | json | detected_level=\"error\" [1h]))"
    }
   ]
  },
  {
   "title": "Warning Logs Count",
   "type": "stat",
   "gridPos": { "x": 4, "y": 8, "w": 4, "h": 4 },
   "targets": [
    {
     "expr": "sum(count_over_time({container_label_com_docker_swarm_service_name=\"$service\"} | json | detected_level=\"warn\" [1h]))"
    }
   ]
  },
  {
   "title": "Info Logs Count",
   "type": "stat",
   "gridPos": { "x": 8, "y": 8, "w": 4, "h": 4 },
   "targets": [
    {
     "expr": "sum(count_over_time({container_label_com_docker_swarm_service_name=\"$service\"} | json | detected_level=\"info\" [1h]))"
    }
   ]
  },
  {
   "title": "Debug Logs Count",
   "type": "stat",
   "gridPos": { "x": 12, "y": 8, "w": 4, "h": 4 },
   "targets": [
    {
     "expr": "sum(count_over_time({container_label_com_docker_swarm_service_name=\"$service\"} | json | detected_level=\"debug\" [1h]))"
    }
   ]
  },
  {
   "title": "Unknown Logs Count",
   "type": "stat",
   "gridPos": { "x": 16, "y": 8, "w": 4, "h": 4 },
   "targets": [
    {
     "expr": "sum(count_over_time({container_label_com_docker_swarm_service_name=\"$service\"} | json | detected_level=\"unknown\" [1h]))"
    }
   ]
  },
  {
   "title": "All Logs Count",
   "type": "stat",
   "gridPos": { "x": 24, "y": 8, "w": 4, "h": 4 },
   "targets": [
    {
     "expr": "sum(count_over_time({container_label_com_docker_swarm_service_name=\"$service\"} [1h]))"
    }
   ]
  }
 ]
}