{
 "title": "Services Dashboard",
 "description": "Monitoring Stack",
 "tags": [ "metrics" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,10m,30m,1h,2h,4h,8h" }
  ]
 },
 "panels": [
  {
   "title": "Forgejo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Repositories",
     "type": "barchart",
     "gridPos": { "x": 8, "y": 0, "h": 8, "w": 20 },
     "targets": [
      { "expr": "gitea_repositories", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Users",
     "type": "stat",
     "gridPos": { "x": 0, "y": 0, "h": 8, "w": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "gitea_users", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "x": 0, "y": 8, "h": 8, "w": 12 },
     "targets": [
      {
       "expr": "process_cpu_seconds_total{swarm_service_name=\"vcc_forgejo\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "x": 12, "y": 8, "h": 8, "w": 12 },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{swarm_service_name=\"vcc_forgejo\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log messages",
     "type": "timeseries",
     "gridPos": { "x": 0, "y": 0, "h": 8, "w": 24 },
     "targets": [
      { "expr": "loki_log_messages_total", "legendFormat": "{{swarm_service_name}}" }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "x": 0, "y": 8, "h": 8, "w": 12 },
     "targets": [
      {
       "expr": "process_cpu_seconds_total{swarm_service_name=\"vcc_loki\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "x": 12, "y": 8, "h": 8, "w": 12 },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{swarm_service_name=\"vcc_loki\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Datasources",
     "type": "stat",
     "gridPos": { "x": 0, "y": 0, "h": 8, "w": 12 },
     "targets": [
      { "expr": "grafana_stat_totals_datasource", "legendFormat": "{{plugin_id}}" }
     ]
    },
    {
     "title": "Total Dashboard",
     "type": "stat",
     "gridPos": { "x": 12, "y": 0, "h": 8, "w": 12 },
     "targets": [
      { "expr": "grafana_stat_totals_dashboard", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Authentication",
     "type": "timeseries",
     "gridPos": { "x": 0, "y": 8, "h": 8, "w": 24 },
     "targets": [
      {
       "expr": "grafana_authn_authn_successful_authentication_total",
       "legendFormat": "{{client}}"
      }
     ]
    },
    {
     "title": "Plugin",
     "type": "timeseries",
     "gridPos": { "x": 0, "y": 16, "h": 8, "w": 24 },
     "targets": [
      { "expr": "grafana_plugin_request_total", "legendFormat": "{{endpoint}} - {{plugin_id}}" }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "x": 0, "y": 24, "h": 8, "w": 12 },
     "targets": [
      {
       "expr": "process_cpu_seconds_total{swarm_service_name=\"vcc_grafana\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "x": 12, "y": 24, "h": 8, "w": 12 },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{swarm_service_name=\"vcc_grafana\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pool targets",
     "type": "stat",
     "gridPos": { "x": 0, "y": 0, "h": 8, "w": 24 },
     "targets": [
      {
       "expr": "prometheus_target_scrape_pool_targets",
       "legendFormat": "{{scrape_job}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "x": 0, "y": 8, "h": 8, "w": 12 },
     "targets": [
      {
       "expr": "process_cpu_seconds_total{job=\"myself\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "x": 12, "y": 8, "h": 8, "w": 12 },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"myself\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Promtail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Docker Targets",
     "type": "bargauge",
     "gridPos": { "x": 0, "y": 0, "h": 8, "w": 12 },
     "targets": [
      {
       "expr": "promtail_docker_target_entries_total",
       "legendFormat": "{{swarm_node_name}}"
      }
     ]
    },
    {
     "title": "Bytes Sent",
     "type": "bargauge",
     "gridPos": { "x": 12, "y": 12, "h": 8, "w": 12 },
     "targets": [
      { "expr": "promtail_sent_bytes_total", "legendFormat": "{{swarm_node_name}}" }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "x": 0, "y": 8, "h": 8, "w": 12 },
     "targets": [
      {
       "expr": "process_cpu_seconds_total{swarm_service_name=\"vcc_promtail\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "x": 12, "y": 8, "h": 8, "w": 12 },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{swarm_service_name=\"vcc_promtail\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running Processes",
     "type": "timeseries",
     "gridPos": { "x": 0, "y": 8, "h": 8, "w": 24 },
     "targets": [
      { "expr": "node_procs_running", "legendFormat": "{{swarm_node_name}}" }
     ]
    },
    {
     "title": "Memory Used (GB)",
     "type": "gauge",
     "gridPos": { "x": 0, "y": 0, "h": 8, "w": 8 },
     "targets": [
      { "type": "math", "expression": "$A-$B" }
     ]
    },
    {
     "title": "Memory Used (GB)",
     "type": "gauge",
     "gridPos": { "x": 8, "y": 0, "h": 8, "w": 8 },
     "targets": [
      { "type": "math", "expression": "$A-$B" }
     ]
    },
    {
     "title": "Memory Used (GB)",
     "type": "gauge",
     "gridPos": { "x": 16, "y": 0, "h": 8, "w": 8 },
     "targets": [
      { "type": "math", "expression": "$A-$B" }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "x": 0, "y": 16, "h": 8, "w": 12 },
     "targets": [
      {
       "expr": "process_cpu_seconds_total{job=\"myself\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "x": 12, "y": 16, "h": 8, "w": 12 },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"myself\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Dex",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "x": 0, "y": 8, "h": 8, "w": 12 },
     "targets": [
      {
       "expr": "process_cpu_seconds_total{swarm_service_name=\"vcc_dex\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "x": 12, "y": 8, "h": 8, "w": 12 },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{swarm_service_name=\"vcc_dex\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}