{
 "title": "Traefik Dashboard",
 "description": "Traefik",
 "tags": [
  "metrics",
  "logs"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,10m,30m,1h,2h,4h,8h" },
   {
    "name": "entrypoint",
    "query": {
     "query": "label_values(traefik_open_connections, entrypoint)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(traefik_service_requests_total, service)"
    }
   },
   { "name": "log_filter", "label": "Log search" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "Traefik Service Logs Stream",
     "type": "logs",
     "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
     "targets": [
      {
       "expr": "{container_label_com_docker_swarm_service_name=\"vcc_traefik\"} |= \"$log_filter\""
      }
     ]
    },
    {
     "title": "vcc_traefik Logs Over Time",
     "type": "timeseries",
     "gridPos": { "x": 8, "y": 0, "w": 16, "h": 8 },
     "targets": [
      {
       "expr": "sum(count_over_time({container_label_com_docker_swarm_service_name=\"vcc_traefik\"} | json [6h])) by (detected_level)"
      }
     ]
    },
    {
     "title": "vcc_traefik Logs Breakdown",
     "type": "piechart",
     "gridPos": { "x": 0, "y": 8, "w": 8, "h": 8 },
     "targets": [
      {
       "expr": "sum(count_over_time({container_label_com_docker_swarm_service_name=\"vcc_traefik\"} [6h])) by (detected_level)"
      }
     ]
    },
    {
     "title": "Error Logs Count",
     "type": "stat",
     "gridPos": { "x": 0, "y": 8, "w": 4, "h": 4 },
     "targets": [
      {
       "expr": "sum(count_over_time({container_label_com_docker_swarm_service_name=\"vcc_traefik\"} | json | detected_level=\"error\" [1h]))"
      }
     ]
    },
    {
     "title": "Warning Logs Count",
     "type": "stat",
     "gridPos": { "x": 4, "y": 8, "w": 4, "h": 4 },
     "targets": [
      {
       "expr": "sum(count_over_time({container_label_com_docker_swarm_service_name=\"vcc_traefik\"} | json | detected_level=\"warn\" [1h]))"
      }
     ]
    },
    {
     "title": "Info Logs Count",
     "type": "stat",
     "gridPos": { "x": 8, "y": 8, "w": 4, "h": 4 },
     "targets": [
      {
       "expr": "sum(count_over_time({container_label_com_docker_swarm_service_name=\"vcc_traefik\"} | json | detected_level=\"info\" [1h]))"
      }
     ]
    },
    {
     "title": "Debug Logs Count",
     "type": "stat",
     "gridPos": { "x": 12, "y": 8, "w": 4, "h": 4 },
     "targets": [
      {
       "expr": "sum(count_over_time({container_label_com_docker_swarm_service_name=\"vcc_traefik\"} | json | detected_level=\"debug\" [1h]))"
      }
     ]
    },
    {
     "title": "Unknown Logs Count",
     "type": "stat",
     "gridPos": { "x": 16, "y": 8, "w": 4, "h": 4 },
     "targets": [
      {
       "expr": "sum(count_over_time({container_label_com_docker_swarm_service_name=\"vcc_traefik\"} | json | detected_level=\"unknown\" [1h]))"
      }
     ]
    },
    {
     "title": "All Logs Count",
     "type": "stat",
     "gridPos": { "x": 24, "y": 8, "w": 4, "h": 4 },
     "targets": [
      {
       "expr": "sum(count_over_time({container_label_com_docker_swarm_service_name=\"vcc_traefik\"} [1h]))"
      }
     ]
    }
   ]
  },
  {
   "title": "General metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traefik Instances",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(traefik_config_reloads_total)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests per Entrypoint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\"}[$interval])) by (entrypoint)",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    },
    {
     "title": "Apdex score",
     "type": "timeseries",
     "description": "https://medium.com/@tristan_96324/prometheus-apdex-alerting-d17a065e39d0",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "(sum(rate(traefik_entrypoint_request_duration_seconds_bucket{le=\"0.3\",code=\"200\",entrypoint=~\"$entrypoint\"}[$interval])) by (method) + \n sum(rate(traefik_entrypoint_request_duration_seconds_bucket{le=\"1.2\",code=\"200\",entrypoint=~\"$entrypoint\"}[$interval])) by (method)) / 2 / \n sum(rate(traefik_entrypoint_request_duration_seconds_count{code=\"200\",entrypoint=~\"$entrypoint\"}[$interval])) by (method)\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Http Code ",
     "type": "piechart",
     "description": "Mean Distribution",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(traefik_service_requests_total{service=~\"$service.*\",protocol=\"http\"}[$interval])) by (method, code)",
       "legendFormat": "{{method}}[{{code}}]"
      }
     ]
    },
    {
     "title": "Top slow services",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(15,\n    label_replace(\n        traefik_service_request_duration_seconds_sum{service=~\"$service.*\",protocol=\"http\"} / \n          traefik_service_request_duration_seconds_count{service=~\"$service.*\",protocol=\"http\"},\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)\n\n",
       "legendFormat": "{{method}}[{{code}}] on {{service}}"
      }
     ]
    },
    {
     "title": "Most requested services",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(15,\n    label_replace(\n        sum by (service,code) \n          (rate(traefik_service_requests_total{service=~\"$service.*\",protocol=\"http\"}[$interval])) > 0,\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)",
       "legendFormat": "[{{code}}] on {{service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "2xx over $interval",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(15,\n    label_replace(\n        sum by (service,method,code) \n          (rate(traefik_service_requests_total{service=~\"$service.*\",code=~\"2..\",protocol=\"http\"}[$interval])) > 0,\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)",
       "legendFormat": "{{method}}[{{code}}] on {{service}}"
      }
     ]
    },
    {
     "title": "5xx over $interval",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(15,\n    label_replace(\n        sum by (service,method,code) \n          (rate(traefik_service_requests_total{service=~\"$service.*\",code=~\"5..\",protocol=\"http\"}[$interval])) > 0,\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)",
       "legendFormat": "{{method}}[{{code}}] on {{service}}"
      }
     ]
    },
    {
     "title": "Other codes over $interval",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(15,\n    label_replace(\n        sum by (service,method,code) \n          (rate(traefik_service_requests_total{service=~\"$service.*\",code!~\"2..|5..\",protocol=\"http\"}[$interval])) > 0,\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)",
       "legendFormat": "{{method}}[{{code}}] on {{service}}"
      }
     ]
    },
    {
     "title": "Requests Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(15,\n    label_replace(\n        sum by (service,method) \n          (rate(traefik_service_requests_bytes_total{service=~\"$service.*\",protocol=\"http\"}[$interval])) > 0,\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)",
       "legendFormat": "{{method}} on {{service}}"
      }
     ]
    },
    {
     "title": "Responses Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(15,\n    label_replace(\n        sum by (service,method) \n          (rate(traefik_service_responses_bytes_total{service=~\"$service.*\",protocol=\"http\"}[$interval])) > 0,\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)",
       "legendFormat": "{{method}} on {{service}}"
      }
     ]
    },
    {
     "title": "Connections per Entrypoint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(traefik_open_connections{entrypoint=~\"$entrypoint\"}) by (entrypoint)\n",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    }
   ]
  }
 ]
}