global:
  scrape_interval: "10s"

scrape_configs:
  - job_name: myself
    static_configs:
      - targets:
        - 127.0.0.1:9090
  
  # API-based service discovery
  - job_name: docker_swarm_discovery
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      # only keep containers that should be running
      - source_labels: [ '__meta_dockerswarm_task_desired_state' ]
        regex: running
        action: keep
      # only keep containers that have a `prometheus.io/scrape-me` label set to `yes-please`
      - source_labels: [ '__meta_dockerswarm_service_label_prometheus_io_scrape_me' ]
        regex: yes-please
        action: keep
      # replace the port for `prometheus.io/metrics-port` label
      # __address__ 192.168.1.1:80
      - source_labels: [ '__address__', '__meta_dockerswarm_service_label_prometheus_io_metrics_port' ]
        separator: ';'
        regex: '(.+)[:][0-9]+;(.+)$' # the concatenated labels look like `IP:Port;Label` we want to get `IP` and `Label`
        replacement: '$1:$2'         # our new address is `IP:Label`
        target_label: '__address__'
        action: replace
      # grab the service name
      - source_labels: [ '__meta_dockerswarm_service_name' ]
        target_label: swarm_service_name
        action: replace
      # TASK 63. Ensure that metrics from nodes can be attributed to a specific node
      # grab the service name
      - source_labels: [ '__meta_dockerswarm_node_hostname' ]
        target_label: swarm_node_name
        action: replace
      # copy container labels straight from docker
      - regex: __meta_dockerswarm_container_label_(.+)
        replacement: swarm_container_label_$1
        action: labelmap
      # copy service labels straight from docker
      - regex: __meta_dockerswarm_service_label_(.+)
        replacement: swarm_service_label_$1
        action: labelmap

  # TASK 58. Ensure that prometheus scrapes the registry on the nodes
  - job_name: 'docker-registry'
    dockerswarm_sd_configs:
      - host: 'unix:///var/run/docker.sock'
        role: nodes
    relabel_configs:
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __address__
        regex: '(.*)'
        replacement: '${1}:5001'